[workspace]
authors = ["Md. Alahi Almin Tansen <aatansen@gmail.com>"]
channels = ["conda-forge"]
name = "Day 30 - FastAPI"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.13"

[pypi-dependencies]
fastapi = ">=0.128.0, <0.129"
uvicorn = ">=0.40.0, <0.41"
pydantic = ">=2.12.5, <3"
