[workspace]
authors = ["Md. Alahi Almin Tansen <aatansen@gmail.com>"]
channels = ["conda-forge"]
name = "Full-Stack-DS-with-GenAI-Bootcamp"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<3.14"
jupyterlab = ">=4.4.10,<5"
fastapi = ">=0.121.0,<0.122"
numpy = ">=2.4.2,<3"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.8,<4"
