[workspace]
authors = ["Md. Alahi Almin Tansen <aatansen@gmail.com>"]
channels = ["conda-forge"]
name = "Day 20 - Mega OOP Project"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
google-generativeai = ">=0.8.6,<0.9"
python-dotenv = ">=1.2.1,<2"
