[workspace]
authors = ["Md. Alahi Almin Tansen <aatansen@gmail.com>"]
channels = ["conda-forge"]
name = "Day 32 - Numpy for Data Science"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
ipykernel = ">=7.1.0,<8"
numpy = ">=2.4.1,<3"
